---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
type: Opaque
data:
  database: cG9sbHM=
  url: amRiYzpteXNxbDovL3BvbGxpbmctYXBwLW15c3FsOjMzMDYvcG9sbHM/dXNlU1NMPWZhbHNlJnNlcnZlclRpbWV6b25lPVVUQyZ1c2VMZWdhY3lEYXRldGltZUNvZGU9ZmFsc2U=