apiVersion: v1                   
kind: Service                    
metadata:
  name: polling-app-mysql         
  labels:                        
    app: polling-app
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30163
  selector:                      
    app: polling-app
    tier: mysql
---
